name       : yadm
version    : 2.2.0
release    : 6
source     :
    - https://github.com/TheLocehiliosan/yadm/archive/2.2.0.tar.gz : 26c79d490f5bc14195e3144e71052a5927da5c16a0d9c4f4f27d8f561569e381
homepage   : https://yadm.io/
license    : GPL-3.0-only
component  : system.utils
summary    : Yet Another Dotfile Manager
description: |
    yadm is a tool for managing dotfiles. It is like having a version of Git, that only operates on your dotfiles. If you know how to use Git, you already know how to use yadm.
rundeps    :
    - git
install    : |
    install -Dm00755 yadm $installdir/usr/bin/yadm
    install -Dm00644 yadm.1 $installdir/usr/share/man/man1/yadm.1
    install -Dm00644 completion/yadm.bash_completion $installdir/usr/share/bash-completion/completions/yadm
    install -Dm00644 completion/yadm.zsh_completion $installdir/usr/share/zsh/site-functions/_yadm
