name       : yadm
version    : 3.1.1
release    : 8
source     :
    - https://github.com/TheLocehiliosan/yadm/archive/refs/tags/3.1.1.tar.gz : 2c7c99bfbea61701aa2bf423caa4e4b2687c3f2d1898de6ca1a17167443730ab
homepage   : https://yadm.io/
license    : GPL-3.0-only
component  : system.utils
summary    : Yet Another Dotfile Manager
description: |
    yadm is a tool for managing dotfiles. It is like having a version of Git, that only operates on your dotfiles. If you know how to use Git, you already know how to use yadm.
rundeps    :
    - git
install    : |
    install -Dm00755 yadm $installdir/usr/bin/yadm
    install -Dm00644 yadm.1 $installdir/usr/share/man/man1/yadm.1
    install -Dm00644 completion/bash/yadm $installdir/usr/share/bash-completion/completions/yadm
    install -Dm00644 completion/fish/yadm.fish $installdir/usr/share/fish/completions/yadm.fish
    install -Dm00644 completion/zsh/_yadm $installdir/usr/share/zsh/site-functions/_yadm
