name       : yadm
version    : 2.0.1
release    : 5
source     :
    - https://github.com/TheLocehiliosan/yadm/archive/2.0.1.tar.gz : 935be5ea014a3b5c17a70585815f8f5f254fd0748cd1c649781807c45e5b26fe
homepage   : https://yadm.io/
license    : GPL-3.0-only
component  : system.utils
summary    : Yet Another Dotfile Manager
description: |
    yadm is a tool for managing dotfiles. It is like having a version of Git, that only operates on your dotfiles. If you know how to use Git, you already know how to use yadm.
rundeps    :
    - git
install    : |
    install -Dm00755 yadm $installdir/usr/bin/yadm
    install -Dm00644 yadm.1 $installdir/usr/share/man/man1/yadm.1
    install -Dm00644 completion/yadm.bash_completion $installdir/usr/share/bash-completion/completions/yadm
    install -Dm00644 completion/yadm.zsh_completion $installdir/usr/share/zsh/site-functions/_yadm
