name       : yadm
version    : 1.10.0
release    : 2
source     :
    - https://github.com/TheLocehiliosan/yadm/archive/1.10.0.tar.gz : 3f77b51197fe14d24f670dbc3e5edc4ae329fdd91c03db297ab929e7bc1168bb
license    : GPL-3.0
component  : system.utils
summary    : Yet Another Dotfile Manager
description: |
    yadm is like having a version of Git, that only operates on your dotfiles. If you know how to use Git, you already know how to use yadm.
rundeps    :
    - git
install    : |
    install -Dm00755 $workdir/yadm $installdir/usr/bin/yadm
    install -Dm000644 $workdir/yadm.1 $installdir/usr/share/man/man1/yadm.1
