name       : yadm
version    : 1.12.0
release    : 4
source     :
    - https://github.com/TheLocehiliosan/yadm/archive/1.12.0.tar.gz : c3d612d01e2027d5f457e0f7d120bc67251b716c373d99fe70638bd86edf107f
license    : GPL-3.0
component  : system.utils
summary    : Yet Another Dotfile Manager
description: |
    yadm is like having a version of Git, that only operates on your dotfiles. If you know how to use Git, you already know how to use yadm.
rundeps    :
    - git
install    : |
    install -Dm00755 yadm $installdir/usr/bin/yadm
    install -Dm00644 yadm.1 $installdir/usr/share/man/man1/yadm.1
    install -Dm00644 completion/yadm.bash_completion $installdir/usr/share/bash-completion/completions/yadm
    install -Dm00644 completion/yadm.zsh_completion $installdir/usr/share/zsh/site-functions/_yadm
