name       : yadm
version    : 3.2.1
release    : 10
source     :
    - https://github.com/TheLocehiliosan/yadm/archive/refs/tags/3.2.1.tar.gz : 6b7e0b32bdca074cbf36e64d8dd528f37c05ce0786fec1099cf374d81cd7d68e
homepage   : https://yadm.io/
license    : GPL-3.0-only
component  : system.utils
summary    : Yet Another Dotfile Manager
description: |
    yadm is a tool for managing dotfiles. It is like having a version of Git, that only operates on your dotfiles. If you know how to use Git, you already know how to use yadm.
rundeps    :
    - git
install    : |
    install -Dm00755 yadm $installdir/usr/bin/yadm
    install -Dm00644 yadm.1 $installdir/usr/share/man/man1/yadm.1
    install -Dm00644 completion/bash/yadm $installdir/usr/share/bash-completion/completions/yadm
    install -Dm00644 completion/fish/yadm.fish $installdir/usr/share/fish/vendor_completions.d/yadm.fish
    install -Dm00644 completion/zsh/_yadm $installdir/usr/share/zsh/site-functions/_yadm
